### PR TITLE
Refactoring and restructuring

### PR DESCRIPTION
**Pull request by Ickerday**
#### NOT READY TO BE MERGED IN YET

As I wrote in #11, the code has outgrown the short script form, so I have a lot of trouble understanding when and what it happening when trying to read through very long methods. The GUI logic is mixed with the wiping logic as well. No hard work really, just time-consuming. 

I have some issues for now, e.g. in the process of removing wildcard imports (trust me, those make such a load of headaches) the appearance of the GUI has changed, as some elements are duplicated between tkinter and tkinter.ttk. I'll probably resolve this soon, but I thought it's worth noting.

This PR will require testing of all the program's features but if accepted, should enable at least some unit testing of the code (lowkey plug because I hadn't had the chance of writing any Python tests)

### CODE REVIEW

**Comment by Ickerday** [comment]
A bit of a status report: I tried to do refactoring of reddit.py but failed when trying to separate tkinter logic from reddit, e.g. praw config, logging in and so on. This will probably take a bit of an overhaul to look like I envision it to, lol.

**Comment by Nick-Gottschlich** [comment]
If you don't mind, I'm gonna branch off this PR and try to keep going with what you've started. If nothing else it will help me understand this code better, so if you come back to it and keep working I can better review it.

**Comment by Ickerday** [comment]
Sure! I have unexpectedly been pressed by some personal matters this week and haven't been able to contribute, forgive me.

**Comment by Nick-Gottschlich** [comment]
@Ickerday No worries, this is immensely helpful for me in understanding a lot of Python concepts and practices for writing good code!

**Comment by Nick-Gottschlich** [comment]
Closed in favor of #17

**Pull request closed without merging**
